---
create_user: sammy
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/home/bitnami/.ssh/id_rsa.pub') }}"
# copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw']